postgres:
    connStr: ENC[AES256_GCM,data:k5LVn1fWf7oSvhjXSmrZ/R4+LnHCiOREWqZEI7Uo9KE9tsF7VaYYG+6DV63ogNj/LAA3HuyojXKvmMGghE6DB6uq8SutmBr1/wlzksn06eY=,iv:hA+A70G8gghjLuajImXF3ZAwNKPIVKbX4oNIIeBtylE=,tag:Q61u8Nmy5KO3t/XcGRqqMg==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeVppWWh0OHVrZGtaZko4
            T1QyN1JlcFIvWkxOa2c2Y1FYbzZSZjNyYm1zClA5dElaTDlLVitnMFA2Y0JKREhI
            YVJORWdCdFhEYzFYQ0F0Szh5bHBpM1kKLS0tIERYMFoxTjcyWkRpTWVvaUhUTGdp
            am8wdEJKeDZQZ2RWenZiTlBiYXArMUEKmyFFBxPpQSAJ5TZ7xy6jKPIysQJG6ntG
            ggKR1t/Fvvl2yqunhfmk4CfOBlIsYVPLlWNhWfnwkUolGdmILEImww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T20:15:19Z"
    mac: ENC[AES256_GCM,data:gRbtxylgrB/2Bvn3PW7EL7ygn/rlrLhzqIItk/oo6uHM28mOaBVCihVgXzfj1tLVbrANtSkbZ9Tzf3blPilUlFcg/dVBttdjM9fYa39Mxm+UYPz80Vy/gF3WML/5Y5uyhdYcQT8LiZhb+OXeQJyNfyoPSVlNuYdnDWMR2vGNjhc=,iv:0W9ZW659TzkkhogTDew/ylfoH8HfHGRfAm70CBRRUX8=,tag:WV/2Cv1LwuszzZnsdDKCDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
