postgres:
    connStr: ENC[AES256_GCM,data:eXdOAehFEd+27VzWOBzuFMKyywj+q3UI1Dy1MdVcG5SIX6iz45MakYFuy+TiCudihIAFpftkP6a3lo484TXo7lO/pEABmycezIr7ZiiXOto=,iv:6lHiu8UJpU799yfJ9HCJ3HVzq2RSotLHy6IG26nMHIU=,tag:nqKuB4FxXK7w889dqpW72Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQXF6QVpOSFd2ZVNTakww
            NFprZS9tTUVIcDQyZXFvMDRrcGh1UGVKMUhvCk0rcGFaTW1EMldLeHg1Q2RJdFIy
            aDRrZFJ5bkJxWnJlRjBaSEVaOTdCQ00KLS0tIGJFVmFiMzB1eFlWWXNaaHNRZkNl
            bW4ydVN5dDFYSFNzQWhlUElrTkMwbUEKqUgE9NPidBqkn9xBgkK+VkHrnEQnxyMD
            7ultcn8D26BCZcuhb0OwTa5s1/ponvsesWaHac9h0XA5idJXRKzP8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
    lastmodified: "2026-09-02T11:56:42Z"
    mac: ENC[AES256_GCM,data:muVMxvquaS2zE0fg3lhptgogYhN+CRFVrjJScMeGeBogQz/ENeBnid+uvOE+PABR3ruho1AdgtphN9zi4KKotD/taK6Hiu9SBfb3/TFGpnCD1yGbZnt+tN3MlhxnwigndzHk1cd0EhKc1OttW6v/cVP1V9dWWgCQwKxn2IPDOXA=,iv:eYhQzg+vzkuC/KWGd+CB8gN7KYIUPSh9ilPw2vN3p50=,tag:tPBaEtWVYFBInh/+r3X33w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
