bot:
    token: ENC[AES256_GCM,data:L60RWm5chNSbRGoKom6OR5ZBhL4lC14Jq17x3Dr8ED7x/4Kk+d2P4wQcCdpprA==,iv:EF4kffmOvl17w5T8AqhygiuQYpmZkg8o6L9ZzFyTWQk=,tag:iiQCoyppw0jKWQMsWAaygA==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:toCkp92ZGWDTzekgcuTYN01VkNB0ctQoLahvMVJssqVlAj70CwXktLXj9yqPmGV4Efhy4Kb9JIQ+Py0W9Sqdwo1vt5/qVCDKTcuN8jBqKxQ=,iv:w+nw9pk5nxrHzBZq17rgQf4EsSqLNMs0nRNB6b+2W3E=,tag:Lt13U2NpVXF/778VhiwTSw==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ25LODJWNHlreUs0L3h2
            S3Jpc2IvYjBydDBzbHdDQVBtMWhTR3A2MnljCndkRUJwdTFrMXZHaVVhcHN3SDNF
            azc1c0t1Y1FrUXJJY2Y0bkxLRGgra2sKLS0tIENVWENjSTA4NzllQ2xIdHJiWG5Q
            WXMzRVVhb0xFS2pmU2JRZ2RWQkZMOGsKRwxFwqmaKjjkX/ZDn+K5Eq5i/KNcBFh1
            BZLA7Vk+EekT1sBfu7g8ySMkmK3D31MmdCB/3FFT6qU1pa7Jfi1mkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T18:47:05Z"
    mac: ENC[AES256_GCM,data:zxA8nvsk21/vvIu0YQ+1iu8hkE29xHGgEZTrfWQ+emxphVjT82MjoFBAlKUTC8G52H7NUQxrkh9sy4jeIFdbA8vXLXosCkh1lPAI3MKzlH8PBW0wLyQoXeqYSfZPh1GgJb+aD+ag09TKwgbDR3ltV9+8V1Aga/+AwZFtCPAeKZw=,iv:9Y7RJECeKwYYUvSQRsx5ociNNMBSu6X5gAiL+Ewl58w=,tag:w5lSzccDCqsSnqJ/eNLYCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
