bot:
    token: ENC[AES256_GCM,data:W9ZmodiPS/bxvm3fl6pNWDced1KXXFIeAwEzOEu227kbiMM4nkXHjlxHGuZsDg==,iv:bHakA1EcMpcqkmTowkMqqAdPPUWP7a5CgKDvb6DbnwQ=,tag:TcDPQKrHUxQUt2rHjG2s1g==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:sflr3ndT2iCC+KlOU5zPicAdU3paQhQd9DVr6M8SR1q4W8fixdYil/l6sUPkQ7nXupAcOtoPnURmgFatX6MkM8XeDR6uf7SCMLfbPSPLZk0=,iv:qMtA2RZmL6c01wBj/wD+jZFRS3VSJ1svhiTjSgQRuVs=,tag:y91UJnfub++WzHtgOjUG0A==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdk5ZdTJ0RUZrK21KMDNM
            ZllrMnBHU0JuMUIzR3F3YWpJc3J4OHNHVmtBCnhvV29QQ0dCZnN3VG9PMFk2aDV0
            MXdkWFlRS0J2N1RqUVU2NThjc3hEZU0KLS0tIExzY1RPRDNUVDlkZUMzbHpVUEJF
            V0FsdjNOSTVIUUhoS0Y1YnlhUVNuTGMKVJ+/fWnF0Uj7diA/QS7L8HtKZUa0t/5i
            FFIksBiMkhYD74/XHq0NRejFaxa/u+s6V7SfZuz/ATt8AO9BGMYbGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T20:15:19Z"
    mac: ENC[AES256_GCM,data:Md7mhTNsNqW3nsdQNpG3p7vMYKHKwTs1VAYCLTV3O9kgsWdBayJpozUEKanK67IhXlLXLLTxlbep2ytQGhzJKaEOlv7Qwm2qUQLVeBAXEdgLO3wOl2UP4EqeNmFwBB50uBS3HlhycjPxFykBBG4zKWtQPqEHZO8N2Vdn4YcRhK8=,iv:5waEh6gAtm2pHza3sRQCddTwAkAl1cpjtIi6XVh3Cis=,tag:CEy7S3NU6hWzmEcdYdr7og==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
