bot:
    token: ENC[AES256_GCM,data:EWlaccBECDOpXx2dYkLo7jaSSGBrmni5FgmGcEqBInkVVMByFdHvtn5yH4hmfg==,iv:Kxs3IOsknBS03bqXEOwmAJYorvGPkLhZNeDGdXfgTwY=,tag:04X+7O+76BgbqyjFrLKiUw==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:kJ2vGR2KPprbw48Z+YosOuqeIDCmkuITaR1+iz8UULjX8EV/fS+7ulvMAk7D7E8Fd6FNs0Cszu+hBhLweuJzyC145XRc/0xiVK1dln0wH3U=,iv:u/lwZomWWG9fTsbKwa3RSVERCCwNFFLGzirMBG7XsSs=,tag:klDJxN/SrhT+RAFxLjaxAQ==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQ21oNlc1Tk5KOWdHTHpX
            bGZlc0tXYmdqamVGdGg0OENDTys5M3BVN2pRCmRkQlNMZ045L1BqdXhqZUpwSVF0
            Y0dETUpuVmFFZTRaMnlLVzd4c0Q4L00KLS0tIGNGdlJDY0JlbVBZdzRWYUFlSlFn
            NjBNbXU2S2VBekk4MC8vNWs0Q1pNZFkKEDR4pe9qKBXPB3r43j/xMVi8g9FsoK28
            AgmqPgvD9xBGK1Ttm7uzqoX7c7MMl55zVhFFNDPUfJaX86oIl0eTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T18:32:52Z"
    mac: ENC[AES256_GCM,data:i+qYlgBpjdWUIRQOn4SniykAgD+cICRjSa3NdSqglo37G2g78PViHq8PYh2EDaY7ixTbwx32WXnPtOxMzHuJ152qSkvAJPNbu2DjC4NnRJI9rsKF0rMVl0UWK0mTcq9kPjoX5z4HXrA4MJaezLBSFoW7orBLZc8Mv43E6qEE0Gg=,iv:LGS7613yij7+59U5sR1VNN4Ne81PRI33JNZjeEJWU3o=,tag:aPLGcWY+5z9WxEspKkBwQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
