bot:
    token: ENC[AES256_GCM,data:NNsB29yJH0QDW4NvIRiD6zsBdxOVWAIPjMbtHA3SXGHorDfsVSPgU9nfDyjqcw==,iv:BV012pIOxYmBsTeETMEDGC4O2ispMBIEtuz5lJKlGtw=,tag:E4qs6B6Qprb7pY9Atkuagg==,type:str]
    name: ENC[AES256_GCM,data:4FGFTuqElqmJlOLe8NtF,iv:a1cfN43FPxIgt/ZzhNndZtgsj1tqMbGOv/wpfx3MJUA=,tag:A4fpdiIJoawAGCqaxtHkbg==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:IIjvoHW2zTQqsHwcNDWBWEp83brgX/tQNNUyxkwRZ9nUOKuw28ADp+XMwxWRiQgKCgb8nqDRWca4Jy0L7xaBDEyfH1lolhZNnY6sra8ZDQU=,iv:ldD/j+kEY7rNznwAnweGHJTd45yXVkp8aXhzmehw26w=,tag:Z4KYul9EumBZSe+/hyhbpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVHdhZStmTnBaaU5OUU9x
            YmIrWEZ2RG1rcUpLbGE1eDVpS2g3aGhTWkYwCnBRZHBPUloyeHJkTW1xT1RKSkpS
            LzN4Y0JUVitPcmR2cjBheVJucVozVFUKLS0tIGFNSk94YlRud0trZ1JhNC9qL0hH
            WXBOeEdxdGFhQVJtOVYxRHUvM3F6VGcKRAMu9DYtPHKZ7H5HJfwximSZEFcXM8Oy
            KJ2Ca2rbT6xFStQgSNMmh7fkA85vicxZlDjA8Cy168jVsgqK7daARw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
    lastmodified: "2026-09-02T11:56:42Z"
    mac: ENC[AES256_GCM,data:j3dc+LKSHa+UoxIyrygdRCySXktqiekY/5JkrlW2fcbFTCswX1conPz7KYyos0NWvp9RngO8oJ9dHPE0ahrbaao/f+C6pGFyIaG+K36Q2kb/QVq/BZQNB4rqCwlwtGpblmHTsnndn4OZCMwi6rnGEHl7vpOaBtQWJ5LcSVutkXI=,iv:p/U6wlqVgNCzXC0DOdGcf7hceeePpcSFkjck+jdElX4=,tag:VSliesRaV/3rK1rSP7h36Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
