apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
data:
  config-poller.yaml: |
    log_level: "info"
    tracing:
      endpoint: "jaeger-service:4318"
      service_name: "poller"
    postgres:
      connection: {{ .Values.postgres.connStr }}
    box_ready_notification_worker:
      count: 1
      interval: 2s
      batch_size: 10


