env:
    - name: ENC[AES256_GCM,data:wVEfyORKd81qU78=,iv:rVntrtfjrmtGPQ7zm8C82Kw5XHGRmm/y2/N0zw046TE=,tag:jF/rF/zW8fgxPKQhRLceBA==,type:str]
      value: ENC[AES256_GCM,data:prMm,iv:AcsFIzYYcfna/de4i3ybhq6qPPFh+sNdML7ogHa5olM=,tag:uaBjaFNF1NXEUxM8NYWqvA==,type:str]
    - name: ENC[AES256_GCM,data:EyzTDWQNk/82d7vIng==,iv:4y0TmHdNKCQh0lHtVJEXQjnGsX9DpcshQqnzMsjbBTI=,tag:h0WFIcNLMkApMa/cGpACYg==,type:str]
      value: ENC[AES256_GCM,data:dVfd,iv:SVTVP4ruxewIH2/yDASmlmx+E8qTCeQ7j4aOk5yHJKI=,tag:fuQXo00bxY4DzgMbZ1sK0A==,type:str]
    - name: ENC[AES256_GCM,data:GNXkuRJsYbHJbSxNCe0ISZQ=,iv:3uH/fdCT+MLEvzW1wAHzMPjhNT6X3amZN64BZJH2P+8=,tag:fMi7BeTzYwj9ev4Lz1224Q==,type:str]
      value: ENC[AES256_GCM,data:1RYs,iv:djOCot8zHoV/c1MZ17oYgcda2vWFKzuvdVdEiU/1GcY=,tag:Du7Kd8KungMfqsZFcG/IpQ==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa1RqcHdabklpdnNUQlAv
            eHFWTU9sVDBSZlFtMGwrMVV1Tzd5QU5IeGdvCnJRTDhic0lUZWNEL0FEa3hLeE5p
            aFRpcnBwZVNQbzNma0ZxUTI0SU8zV1kKLS0tIGMwZFAyV1ZkYUdhbzc3ZFFMMUEx
            ZE5ZaVhrZTI4anJ0NUNtREM4eWdrMWsKSIBp7/R5ICMJ3eKHArilD/N78eneQ9PQ
            oQ/eH/0KYkQ6fA++W4PHhFgJHqSORICKWDIQU22r/lTE0K0soj25SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T18:32:52Z"
    mac: ENC[AES256_GCM,data:Ahf7JJL4GV6ebIsFKY7Bq5RPrytpNg+6fTaAVeNsYRlaIxGFub08wuB12wmWOZLNU0N2KI6BdQbf8JjH28fLmB5pjw4LWkjmQ+oCfjAs1eTCvZXOl+CBwrg8qH6Ub/I7ZYqpGspuOj/9iCGR/fs/pyhAJ34dvTSsokE2cFI/Ls8=,iv:L9oW+v81RGK3CoBmNS27uZ7N86FNupwo4m8KDnHLlAQ=,tag:aR9tR82vMBnzWxMLncDz/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
