env:
    - name: ENC[AES256_GCM,data:I27izst2tAa9wwM=,iv:zO4QDSEkzXU1jKTjiSaFeqsDdh5aqp9kMQEPAxpS8wM=,tag:FtX+RRU31pZilGxEDvCJBQ==,type:str]
      value: ENC[AES256_GCM,data:4Oc/,iv:DJq4AIydWL0WswwKpbcvFzD4zS6pbW56olXkAYZhky4=,tag:BoQiSReK8XfR3Zg/SrGoUg==,type:str]
    - name: ENC[AES256_GCM,data:H6S1bLV9t3fcf+v1OA==,iv:YsJHD1Z7Wmx0f3WVbo5tOCJcJzf7JyDmVc4p2KHREV4=,tag:LwNrn3tQK7AfNX73HffJDg==,type:str]
      value: ENC[AES256_GCM,data:8H6f,iv:ckbYgDJUtYUydHiERcWG/YQ7TrOUPMraw7YXcw8MxFg=,tag:Vcz0f4kow3W88dTjLXSK2A==,type:str]
    - name: ENC[AES256_GCM,data:H4B9Dq1avThwJk52+zw339A=,iv:vhAChwDKnTf7TBx1x3IBE17aQRFkqEedmSP7StCNsAQ=,tag:VBqa90WqGfrfKd21H8pzYg==,type:str]
      value: ENC[AES256_GCM,data:D0eV,iv:P4ZGNg/eaHoZTVWClf2x3/4uD43Ys95pNl9X2ZWiIfo=,tag:D3m68CxkzRL8jcSn/EEDMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhd0lJdGVOVkJOTWtrOThv
            aE9IdzB3UzB5N21aRkdIcjhiSU9DZ0hybzNFCkczYUwvcjNNMmhWOEg3WU9yLzNw
            MndnMmNRbVkwYUlmMVVQTjJGTDFEOGsKLS0tIHlXOHFhZ1lmMmNjSlJSTUJWS2dy
            L04zbFNBb2RkU3Q5MzFCWnlJTEowckEK7xSm9q1u1nPXuZVXlc8mFd1jTfK5pRaP
            V5xW84w+2YW8BQaUdDuYTgLv8RddL7cxAE7Vg90v8VQxCxs/baS/Zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
    lastmodified: "2026-09-02T11:56:42Z"
    mac: ENC[AES256_GCM,data:8Q/g6x+ewDlNYkaPtBc+iEGpNulUZ9GmcmIJ0JdMcXzIksA6bLhlLSIswI5QWfExEAmh+WZDi+v+GZRTUw/ICdG1Q/RNoljIZwLGKeaWup5mGYp1gPggDdmfcAkpCvLUmNtReRk9tj68HRYUagSqUGN4gdp1fujtHlSszRWWXZM=,iv:0bbhorDZMLVqoA0FAbnEZ0KWBeEzzos2PGgUMi2mgCo=,tag:CBvw2YazEYV2ugi6DmYCCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
