env:
    - name: ENC[AES256_GCM,data:bq/xwe+Hi1W9ULk=,iv:UkVYCMy4cQi52vMJAs0yA2vnAAdrJQ/X4YV5pKkZaxI=,tag:nLkCrc/wN3gQr8SsQCgvDQ==,type:str]
      value: ENC[AES256_GCM,data:oRZB,iv:pKr7/Yq4eBXqM9G9AlpatAyzxnBLJQc3a32QdJHi/Xk=,tag:8DHdkf0zVXEb0GF2T+/BJw==,type:str]
    - name: ENC[AES256_GCM,data:fYKnERy886MeGgHl8A==,iv:LA722oSdiCf/sL1eZPIY6+HovUvLk2jaqSXrDkAcCkE=,tag:9LxNbn3ms3etsEDoGiXEQg==,type:str]
      value: ENC[AES256_GCM,data:9H8A,iv:YWQfr+UTDdh6XUx+eFhWJ8Jf8hOzzo+kxw7vG5YvCuM=,tag:knRAuqulgdbkfeXa//zDCw==,type:str]
    - name: ENC[AES256_GCM,data:Ee4LlBcX2+Venl/ebUshadg=,iv:r5Hly6KRJF4uNhBhR3SYksWfzlDELQ4zpPh2+or2hmQ=,tag:hXg9qA03Xm1g5+xdVVfkeQ==,type:str]
      value: ENC[AES256_GCM,data:V4iQ,iv:r3VLlId+lOjfi3BUwlA0z2T2gZNxCF5QkHjUv+DXCRw=,tag:d8OardQV2wcwq5xvt/rDAw==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5LzZjSTRseVRBdmhtZTE5
            a2tmU2RVZERjajNyaUc3aW9LMjZTTVRaR0RnClhSTmtMeWJZYXIrNFNmSDJwNjZB
            M0R2N2o4eVN3TEpHQXNSSXVGa1drNU0KLS0tIFJldjJMVmtmQkVGVzE0bDhqTEJ0
            WUdYekJlUThFckdyeVlSQTUxMHZ2S2cKFRiVDnfGjwideqiHYCxY8ShL/pxXoxGC
            miPN0JxBDP60QSSWdLuT4ZfDnteHieQvxXjRQNR6o1uAyvoUgxrjNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T20:15:19Z"
    mac: ENC[AES256_GCM,data:aIFMoTBNVSoxgCWymtC1Czhptf7oXLNTfUSbngKNbmxI2LfSNJG3lSe/1X/rHwx/LNJOdmN2ls28RbqkBBaejI2hAAd6zNIR9tdTDtWfQJs5cUTR17Lxf2A35GodbOmCRzwIu/IEeEtYEWtToY+o+ZXAjNO220DbhFCGCLCDeQk=,iv:ehcCpZt3P81VWKtpZ+r3pN59el2anB4zg7moCbauSLw=,tag:pnCHIIurVakWNn8C6sysag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
