apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 12 }}
  {{- end }}
  selector:
    app: {{ .Chart.Name }}
