apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
data:
  config-bot.yaml: |
    log_level: "info"
    tracing:
      endpoint: "jaeger-service:4318"
      service_name: "box-bot"
    bot:
      token: {{ .Values.bot.token }}
      webhook_token: {{ .Values.bot.webhook_token }}
    postgres:
      connection: {{ .Values.postgres.connStr }}
    open_box:
      common_wait_period: 3h
    box_reward_percent:
      normal:
        legendary: 1
        epic: 5
        rare: 20
