apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Values.dbmigration.name }}-cm
data:
  dbconfig.yml: |
    development:
      dialect: postgres
      datasource: {{ .Values.postgres.connStr }}
      dir: script/db/migrations
      table: migrations
