bot:
    token: ENC[AES256_GCM,data:h1i9px1rXwzjkztE991c7u9pZlsdbfvhGE9uE2xfmjF9h82coFFZmHDR9TEARA==,iv:6p41BZP4DPTHbLIZp/vhd2O2Phg2uef1kwUEGaW2Kaw=,tag:n6nY7PtVWKsA3VDNP70DdQ==,type:str]
    webhook_token: ENC[AES256_GCM,data:86SZNuNHtmEMKjl6SdhP,iv:wnt3MJTilfix6lTlddbv6eZHMDu4XmAatQgTMp8OP4w=,tag:DJBL3qaV9q23MTvx5EeDGQ==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:XeOkQEMUvGxVG9HG1+Rao2vEmTaHbePfTVFA7hpC1njYb3OGnRcsHuwgz7RghntT/e/ufXJk+riZKihLVgv2O9VkJtZFAdFuABZR9VD6kcwjL7Ja6Qc+bucb+z5ZW0b1hlLy6m1WQQ3tYmg9L5JoNe6B76HLKuGgCfuW2RL1TK0uUoLyW7YatTbX/eHhj2rH4HPK8fWNFEf6DeS1bLMh7u3xzVmc4w==,iv:Q5TZw06RodkLt46BsnoUxeu6bj+P+X/A2IzJbWsJNQE=,tag:0PXEfOHosGQtOd/YZjFmvw==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbWJoQlkydVVSRFBSYk45
            V0VkZHpNYmJWdHBkdmFtc2Y2V1JQQVZjVEJzCmdrNlhucitkYlJ4ZVkzcmNTUkc4
            Vnl2VUdWNzJRMDdMVnJFbFRoWFlrU2MKLS0tIDBGK3ZKNFVTNm05UUxhUXJhdmho
            ei9BUHpvekM5emdXbjdxbWFLKzNHV2MKF4nRGH/igD8EJxxeM5NNpIRCuBYuijGV
            VrpserB9bQWukMr859WgxAc6+XejlIfk8sXNbYuFMr7cxQXaf/dubg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T09:27:56Z"
    mac: ENC[AES256_GCM,data:RIjM4wV9xQgKBpx8jBkxvLfOpKG67qB9GTvTC67vn52ha73R4g+wqiw7h6gQd5B4BPOHwaWjFFLiep/bkp6q7/VQ9wxr5VFhd5JKZZpVWl6sJmL5a0+B25Np1LAhS1RqF0L4FnDC02P5F1uRcUiqcBuesdOgMjzUI8brPmB3TWU=,iv:owy30hHoVUbbhB1+l5Qg4T0FA/YaRExGEL7GU7pHIn4=,tag:di71kUHiRxQm8m8yJaAXbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
