bot:
    token: ENC[AES256_GCM,data:FeZQeVEuhBdiVkPpCYD/VMJLPDyjzeLkV4X/dm84Xjnu2D9vn59qrc1cEg+/Bg==,iv:h8KdJ4HfdErKdOGLn2bQ3dJ23qxcSyDG0RMa0M2/16A=,tag:ev9ffWpPLBVHNmSdE518Dg==,type:str]
    webhook_token: ""
postgres:
    connStr: ENC[AES256_GCM,data:ixsU6CHuTu3T3IdgOLHTf5RooCa+OyJlytCX6hsf0qwA25k3scCsGE1n7DNWRcCrsMREdQYFnKWB9z3i5/Re5arj/ssDeqNiKECCEkg33kBFWTz1H07fzX+lDh2AhSnTvZUdcgDCn7zDMTSbl5p64HuDZgyYFX+1QpCLfgrhM9V0K7LoYYAkvBXRHcOF4zPY0fWXrZitpWBCAkAAGhB1sjJyS3KHYg==,iv:ng17Hx/waVJEAhnTmpGeGrb3dZ8SkIrkANkIGEfwR/8=,tag:bkBeckgmjjMXwwOm9Tmjqw==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WTFYbWk5enZXTmNVTERI
            Z0pyay9zbW03SE1EZFZxR3NINmRuNUpVRURFCkVReGtTa1BlcGVLQThLa1Q1WHJY
            QlFOQXhMZ3FYcTBWWnVVSTdFcFZieUEKLS0tIFEvTDF4ODZTNzVzVVdMRDBOL3FL
            R1UxTFJLZVpMbkIyK3U1b0gvRFlBd1EKeGOqtJCooeFgyvhUB1ZWzJ8JojATKF/g
            g469ri88Qt6Oj663c2sFkreL0CVHfEiP7IPuc/G8IKA9thrSqYp18g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T12:57:37Z"
    mac: ENC[AES256_GCM,data:s0IusEiZ5oswBNYvMPrxKplZ1gT3rH5ArhrJbtPE33/P1AbcwHyc5piA5COHxtlKG0IG/9mfp+Ej/8xzBziuS5/Oj8cjRnqEkwioTSu99u209rcTwEesu10n9rj0050dp5L9JoNXe7KyH4FjNgoLiMRx8km+2EejPFmc0H71FqA=,iv:Y5rJvcxP/dOlUiKKhxoKHUFCIE9tTc4j2A77gCQNS20=,tag:vlTS0u8q5IkkIjHWhH6b2g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
