bot:
    token: ENC[AES256_GCM,data:4GDlGGcfbTv490cWmJjcFJ00tOPKLG1UYk+UjiPL8kbNJwF2jnV2d93AiJH2qg==,iv:tb0XCPTEU1P+4yegAAgww3x4dl+z4hZV/74eOhKkU5E=,tag:pzct9yc6VosONQYNkd60lA==,type:str]
    webhook_token: ""
postgres:
    connStr: ENC[AES256_GCM,data:hYgNDGWio6SPeSrMKFTp8/049H/V6b59HNenZHoxqW2VXodjNKgmNNYlLrBRuejvko/cpVhYoEVF1S9wj/RA+vQrhBbhiPNg71MlAaB5zDzU7PcO6AxNNJaMhu0IcOsUOKerwpxMHIP61ijzyWfeV4sg6mDtjqcpUAfP/tjPQWEeS1uyyfiIiHM1P4Uxbj1yuvhT4oCCs7m7NY7BGoDlpUOUNUHNCw==,iv:L3Hsz2CanCf2h208n65mApzzRfqL2vjW1ZIflmZQCE0=,tag:8m/Tv/dq8Pkw+glVS+Dkrw==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWCtkOXVkeEFtcTZ5emph
            bzc4Mi90bysvQzkrTHJ4YjFyeXQ1dEVmMVdzCmdXK0JTcmdqNmorTHIrSzYwSWhX
            NWtTYlhoUE0weEpvRXRyTEpUSy90SEEKLS0tIGFRZG03Qm9DbThYak1ZeE9JSWdD
            blJZM0ZDcWZKZ3JjRU91bzdaMDZYQ2MKu15NhYPi0y0AQ87tWLuh5fZ6W6+1c10R
            JG45mxnXVe4Vs1WIoyCptgTnG5wPkcu9lGlIoZbPWQwlOMIZFwJNAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T17:25:35Z"
    mac: ENC[AES256_GCM,data:hBsL85/x9ePcoRAYTqhniuXuCqo+2sl+ZyYSzc4fnQDdYOJRz1Q8xIfDcpP1e4ur3QfUX8uzpo88uBFrg6y35K8GKbqRChGCUxiXn0lK7EhM7EV1i+wj8JtQIlsoXHvggWWWS7EMXWluw8eLBW3NUQca/yomBOWLd0r0zkPDh9I=,iv:Gh8MjFMvBdQAytVg1HFQePQMB7sXErKkgOxKF+Xd3Y4=,tag:nixX7RwlaEfgisMAP2e2gw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
