version: "3"
services:
  bot:
    build:
      context: ../../
      dockerfile: script/docker/bot.Dockerfile
    depends_on:
      jaeger:
        condition: service_started
      sql-migrate:
        condition: service_completed_successfully
    volumes:
      - ./../../config/config-bot.yaml:/app/config/config-bot.yaml
    networks:
      - bot-net
    
  poller:
    build:
      context: ../../
      dockerfile: script/docker/poller.Dockerfile
    depends_on:
      jaeger:
        condition: service_started
      sql-migrate:
        condition: service_completed_successfully
    volumes:
      - ./../../config/config-poller.yaml:/app/config/config-poller.yaml
    networks:
      - bot-net

  outboxpoller:
    build:
      context: ../../
      dockerfile: script/docker/outboxpoller.Dockerfile
    depends_on:
      jaeger:
        condition: service_started
      sql-migrate:
        condition: service_completed_successfully
    volumes:
      - ./../../config/config-outboxpoller.yaml:/app/config/config-outboxpoller.yaml
    networks:
      - bot-net

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "14268:14268"
      - "16686:16686"
      - "4318:4318"
    networks:
      - bot-net
  
  postgres:
    image: postgres:16.3-alpine3.20
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot"]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - bot-net

  sql-migrate:
    build:
      context: ../../
      dockerfile: script/docker/sqlmigrate.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./../../config/dbconfig.yml:/app/config/dbconfig.yml
    networks:
      - bot-net

networks:
  bot-net:
    driver: bridge
