bot:
    token: ENC[AES256_GCM,data:ww89/DsHs8fjukyUasIay3mJcuEJZjqK/52me3uIRnjcK1op+gcUZdiHJt71Wg==,iv:Y/z0X3HE7JVMR53ynkiVvEDLRMBKu+viIP2nF61GSH0=,tag:yD8M0UD6jloa4NOLOApkyA==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:NtPwrC1tN6xsRNTb1486ursIVupCMl4vclrD6cV6Bos7KNpJwuCEYaqrZfx0vXEjOksJWGNPixN0CpMBThe47PfiZKg4qLqcneDldVZnhLQ=,iv:PS/URInkZU2Q50PkC1xu6L2cZy65i0ZWPA5v1YHGchs=,tag:MPjHI+kZQrlbK8GT9IbOyQ==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYVNTTDlLY1B0VVpoU3B1
            Qk9rY2M1dHIwdzNPNlhNQXRESE0zaHNOSVc0CjJOM3VpZXkzSkc0aXo2WnFFcVFC
            YkFZeklFMSszTC83eHMrTnRaRWRWUEkKLS0tIHZrUnVHWm9td1c5RzJCMStUKzFK
            S3RpdkpNcDc2TTErMzJmNFFDaFNUUVUKUzTQzzE4L9oZ9YOFDPbPpNZsZmQjGGEn
            GGCaxOe+dvyOe3NtCBPUvIdoKhXlzdE2cZl2zckILW+SrW+9Mv8yzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T20:15:19Z"
    mac: ENC[AES256_GCM,data:/GRY9F/kiddm5p/anZaNPrkbScnKTDkO0XagMSQVBszvAocJgCVoWsa9WBx+XMAcMHcCLcRkg4f8BEDPAGCmmU0VbQHEhDYOK52nvoGLczFqy9WMx7dGbTM+2DvSo/1TRN4zWeYyz+iF83PynBtLUdAwlKnV13YYPf1PNa5rNVs=,iv:EgIs7lMehCTSxu8xAdu2KH09T6VUF4jg9+77gicb5O4=,tag:sDhMpW2P+Ki89/TwuXqT6A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
