bot:
    token: ENC[AES256_GCM,data:/Wby2eof1y9Yo38m6x4RYA+lPNPR4X/nwJSKGbnVo6CkJV0q2Qq3dqpZ4Rq/0g==,iv:EYwSGPqzNusIJJsKyAF9zt0r8B7N/l96zXKt+0t5Skg=,tag:ApJE6Dfx4mXUa+GFlB/K2Q==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:SI7QnCu5FWHkfx4tsZvjT/+xFkjmhKpRXHVJCgf35id3rSYQiX1xqI2FkE9HMBxFgirej+XrIm4xWLdpqv4e0cf/Nt7+XISY5jhNIKoymfE=,iv:tqDTOOxjJ0qiF+sv7u7Eolsoo2HPwDENLmAA8qrb8w4=,tag:z1dc0+PF/ZLbTeGpwhkWNA==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NmRucmt1NW50TFdtYVZ4
            d1RpRDlhdHNCUTkzODJrL29uTXVzWm5XYXpJCmx5L3RqcVpnYVU0MVAxalRIL21Q
            N0hmOFpSMllHOFJCVzNXNzVodDBjVmcKLS0tIGRYYjk0RjdhbzZ3TEVYbCttZ1Ir
            R1ZSQ0FvTjdEdUhBR1hIbjV5KzhZSzgKhuncbuDg8mXXXyHe+hXEDYt+TJSqFLGe
            yPqJQzV3Jxjqw0KdN9klMHTT4l2KZ08PkDoGUhPjtWCbVxgqsH48qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T12:36:36Z"
    mac: ENC[AES256_GCM,data:pEo0tlnIJfgI6oAeTo8x8oUAfKlm2if+WKrsFy6qTYb9WApEf26mzWergmM/WEF4d4MdhqzxW51bl8jVWVrFP61YjjQ87SwUOkDFUljLb4noxYYwYPDmvnfNtyshtY4oPGjjA2SVpPtxW2JQo2sCKc2IEqFVq95eWSnckCPiD4w=,iv:sgV68JuMwYLCGpTRLLE7jCaSQVTMfMdI0UsxcYgt9Y4=,tag:CmavoTgpY6NnGboJaR60gw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
