log_level: "info"
tracing:
  endpoint: "jaeger:4318"
  service_name: "outbox-poller"
bot:
  token: "bot_token"
postgres:
  connection: "host=postgres port=5432 user=bot password=bot dbname=bot sslmode=disable"
worker:
  count: 2
  interval: 1s
  batch_size: 10
  max_retry_count: 10
