log_level: "info"
tracing:
  endpoint: "jaeger:4318"
  service_name: "box-bot"
bot:
  token: "bot_token"
  webhook_token: "webhook_token or empty if running in polling mode"
postgres:
  connection: "host=postgres port=5432 user=bot password=bot dbname=bot sslmode=disable"
open_box:
  common_wait_period: 3s
box_reward_percent:
  normal:
    legendary: 1
    epic: 5
    rare: 20
box_costs:
  rare:
    amount: 25
  epic:
    amount: 125
  legendary:
    amount: 500
