bot:
    token: ENC[AES256_GCM,data:DIydKLlhDuIVaeTzSXHgPpFEWE++yjFHyV811FvEJnyS+XvbdmZkLQLv2LLjDg==,iv:EXforVpLU+D3wg1lQcILccrW+RL6xDyGg3BVA+0oM/w=,tag:UStOFIu0X+etylrZKc/rMQ==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:g7REtp1PedgYPwYzRLgFSlCgu9elXsuxHo8RO7CfXn+oXWZq6mlFAhqzfgwuJbG6Sf3+YwfwykX11hWz7B/IAnHTmTAzNvHg40zXOefwh/+naC4zxCfvHj+f7TCuk/6bGy8CQ9nAkyjQ5x2yCRzTSDvCFAZrgnxAOAxh1u7K6OGbsBvs6dvg0yxl1LJZuR/Dit/8rTBoFu/XIs/IK4lOVDJt0o4XVQ==,iv:ovtEyJvQMN1u1kYwORafl++WnNR6pEsLP5zQrAuKiwM=,tag:Y0wqU3JJeZ9qB6Bp4d2gRg==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFR0dwd1BaRTBpMmp3OERR
            NlJHMHFUbitqRGp2ak5WNXAyK1pROUVUK2djCjJESCtEbGFZMDBSWGkzcXNDck9C
            bmljUnpyVWdwR0tYOUtPZjJnTzlDWW8KLS0tIFJCWGtrQTlsbHNNMDNXbEQwTy94
            anFoZHZYVVpIY011ZTVGUWJrTVZ6QWsK4+OOS8nTrsbEaPbbMqAjxTxssWvDBGD2
            ANpwMk8wi0PL7MSVEhk6LVtAZ3KvmIwtGr9MDnKJEGcW3a/UZoDgpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T12:57:37Z"
    mac: ENC[AES256_GCM,data:LxoCANENxJXMU9WmIB8ueOZ4gu/rNaiecycvfEKJoPRRK7ilk0asTp2Jvr08R9b/tasW/3FX4ECVCDWuNSaM0yRRomTnf2P6iNt9jRmxt4Yt9NC16QV0Frl6IIOwzLIgeMdf2VYc4MlOSNMooMbBQxRAfgXrX9fV6iDzRrQ7vjQ=,iv:DN0FerlgethxLeXc3AxrRu+YCV0GUTzqCoD9mxLUdFc=,tag:0xSvOTU6FdHFTG4e1+CU0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
