bot:
    token: ENC[AES256_GCM,data:9/6b1mJLCF2PVDT/cNadvt55nQZM6ekE3kbcWGYVlQ7NjaNNMUo6yaKyEfTpdA==,iv:xe2kJs82HguwhhMXptOqZAt0D7syUHZSXGv/KrHNPnA=,tag:6jSiX4nqtLb6pFDgMj8mFw==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:3lLDzX+ma11q5xHID5IdxCz65hhNw4XzEMQYT09FEF2wynakQA7bliF/MhxqeTRAgBvbRIKbaJRCDN4xptmZ9pnwLTEEcL62CPBPmmOy2lc=,iv:I9Tqksfex4E/wPyU6TJ04gPX0RrqFV7ojXeL7lu4vyw=,tag:87sEmOkefQ/TeLiqMGZJbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ajFVM3pwUFdkcGpFRnF5
            YkwzRGkzQW5QaUZvM2ZLeE5Qc1JUTUxENnhVCng5b0RFOWp6R01HbFdHSEpQT2Ft
            N1N6SmdJTGQ4azYxTWZDQmpXeEtsb0UKLS0tIE5abm0xNjNZdmVHQ0l6SThuVVI1
            U3RueVNpVmxvdHZiK3k5dTlxWEpnYk0KQOowbfK0SfztLgu9ug4wzxPJiTjXDmx9
            Emd6T6h0iYJ5WUvC7bHOd6CDOOg92naGphat9phrE1wNr8RkeJuHSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
    lastmodified: "2026-09-02T11:56:42Z"
    mac: ENC[AES256_GCM,data:LpLyDu5/FFU1QRwj4ucigtq7/innThWqQlpJOe0/O2GSiqhhY2yXj1sgxE7w5ThERQGeiagdEDJLU050/Ub/o1FAXVCQfA4kITT8D7RvqEpANd/pKmP06+4XX7u57z1iD6P3tC170bYtBhZlefpw0LmAdy79JhJomU+N4C1HxLE=,iv:x74LkD/wxM3dUcfWrt8hbLVCua7KBLk54F/XImih53A=,tag:24g5QUb1gStab35Bg79dOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
