postgres:
    connStr: ENC[AES256_GCM,data:fRx0v6u9vU6sZ98NRuCI/WmrDRJuCTMVrVpG9MvKW3ObN+7GmS5UEr4XRjfmrI1S6Q6Y2xkn9T4jFk8w4FC8H6/81e3Cf586+dG9D9BqOs0+AHVWeh1ByQauakCxxk6k/OVy5Wbdx2mO4+ker4zBnBJYqrvA9+orkTz4QLGSByDgbmIOaT3Sse2GLiQuIJ80bt9EHi7XXdjIIvnjF+ZF3gajTO8npg==,iv:9zoJCf6fYzxnH1U8fOssxB3BSWOjOjqUksXLoTh2fUk=,tag:EnIUA8/ICgq+nTS2wpnxiw==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZWllN0dIS1F1bWU2ZTBV
            Y29NK1UrRG1aaHJVRnlpNEtkQW5vV1Q5WkgwClNhRnBmZFNBNGlnUXJNbDlxZ0cw
            RG5sR05LTVViZFd5RWU4UGJYOEMxaE0KLS0tIFNGZjlQUER4M0VCRVJFK2FEVFFm
            THRHaEFjOTBIZmFZUDJlWFlXeEd5TWMKiUlzXyZJYQrI2QYW4wv6irO5Vf7r9YSQ
            Cd5i4lrUGbncxZ186T5WJxYEL4IouOi79up+SrwuCzbvWvtkx47UKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T12:36:36Z"
    mac: ENC[AES256_GCM,data:2R2nxfE74q46TUPqHy3z51XiBJet+epeHhoZHCjWC/FSCIH5oBgf/5QbBj1ZR5P9+FVozHkacchwzOav+rq+2Fv/5omgSdJd1LxFhHR/eF+AaN0uFx5F859ZVnEkfCVUYfHp8o/EXj7p615J6pxAy5up9YMnxfgcOwtRrMcO2r8=,iv:1v/x1aerMO3PH5RFs3w3lXuYMR/F/cY//FarVZUByLY=,tag:T/rYzqyZr7Ov5OqhzhrKUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
