bot:
    token: ENC[AES256_GCM,data:x/vkN9dmi0sBXM/GC1m1H9RyebOLy7Ytv/SJvWFF9/zZ4IHLyREa0VjVyb+Pbg==,iv:ZioFZLNdDeMTc3QCTWgZTZnLJWs8FpYxzUMwMLaqu08=,tag:pYJ7Awu0bscZZxoX3zwTaA==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:7lMQvLGRZIhdWoG4t5FlMgBaqnXpS3qQlh7p/PtpiwdWM3kNpOFXlflcC8nVQxycJ43yBGXbCD1iZdkFqM9an4FOaLW99ugMEccgOo3jPmBeGe0Ant57PTGpX5yrDNwI2cjxJRgB9eBnDCyTSL5E8awyA3AdnC88O85Ue2mkK5aCljC6w/f+fanH/e2cCKtD5YD9NoxbmIunrI0ekPxzwIRGoKL7TQ==,iv:YKRKeEMK8/NJ0wOEPAxta7S8mw5fpjV0bdMFRQUttD0=,tag:gcprmGChF9lDu9W5QcxhuA==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRXA2d2Vrc080VTJ3UGoy
            YkJPU1BEdC9GTUVaWmpXamVQYjgxajkvZWp3CnZkd0daZmxDRFFhclVxNnV3Qnpi
            bmhCY3o1NlVDQy9WZ0xleFg0eitmKzgKLS0tIDJIS2ZMNUM1bTgvY0FJeDFmRkUr
            WEMzN3RuQU9NR0FwKzFoY3ZsMjJFazgKr7mlgODFR0pc8lulz3XNdsqRt5G4n+vn
            6zVbDUwTHtREA7WHT8Yh/bYA8gitduXlJ7v3wRDZ2X+NI/KeJQyIgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T17:25:35Z"
    mac: ENC[AES256_GCM,data:12gsVSjW12zNEeB10Af/EgWbEyzJMoyvgAlnNovuw7mCeDwa6moZFTcFLehDSyNvIJ4LWgF739cLCAMeDf/65OnsjHRP9/mfmMbUtJqB4xCk/4ZEINdeoJR6FBcnAkn4EJQQVNAZulVCcrMdIL+7EaJf+NaG4ioU5p3R3FsjpCM=,iv:loimvKI6mnyoJf+eLt+EF29Y8BnrxyiBtAgCGqM5jYI=,tag:aVCNyoLuyeZfUXC0RHVVHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
