postgres:
    connStr: ENC[AES256_GCM,data:+ggNw0o26p3tUuBravyh9B/L2sQjHriJewg4/8r7MPF7SiCABAHpt2ll63cAjDWPWi7tREi7t1igkpwJZwanzE5OhR4Q8sh0nIHM8MaW6nQSsVnSP9CXVZ+UZ0vT884ewwaof6mlK0GQ9zUvgH2pVayXJxb6cI9wv1ZYsSyi5NOLnxumFg/mAHIo4edUKZp96STGQ1A4Q1WxSiousHclWNWEzt1vVw==,iv:RS+rZY7tq3tSfMmKJtkfmiVSpSgmHvwyDK89jxk6TY4=,tag:Mj99TleBHanJlUX0evW0Sg==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3c0t2eFU4bldpbW41N1JE
            OUp5Z2tiVzl1c2hwY1N0eGFCOTByUFRVRXpRCmc3THB4VEowS2lzb3I5YUMvOVZv
            ZGtJUExiZ2dYaVQxZURFUEs0REdrcXMKLS0tIEhrQXFLVXpxZTRxcWdGL0FCOXc4
            UmhBME9Mb1ZSRCtFTFZYekplU1ZMdGsKiYR0Sv02U98Q2mXmc80cM5T/lx+W2q6n
            tcjCE+FdhpSIMFYIwGsV72WuWKGjDtF/iSVs+TeD5AZiHfgOmra2Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T12:57:37Z"
    mac: ENC[AES256_GCM,data:P/4ZmE+Zzmvvh1iwgsZ9kOhvpbAubyMObuYM2wXL7kY86V/KQfJGM+ejsuE3GBBCLcAuAse1cuNbUXyKKhc093v4mzHtnP2QZ3f8dOH0WGE2rZKsHRkuUiwXodyvaCs+mqpq8Xcf1EScD73XNCiXb+ds/+rGlni3u9mKO80tQq0=,iv:kVjgyhlWDqpusj4f2RJWUHO+avWGlSRsGgiIYo+PW4M=,tag:Cd0OwxE8Rx41d067nBB3yw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
