bot:
    bot:
        token: ENC[AES256_GCM,data:OV2Jc4YPyNahj7itFG4u6RFNGpldlC2Wz8nPtoSfHUoNVAPFEuGGSG7HMwoIFw==,iv:5mNUWI4CKRxi8zONKbUtOK/PJRbCLj0fZAJFML5p20Y=,tag:QIFUeoBKXzJSk1YRmNWCSA==,type:str]
        name: ENC[AES256_GCM,data:4F30vPXNuLZu4Q==,iv:cjKl/iuFES/gOnZEIAXXU50dhY+WdNF3cTwPZUV3Ip4=,tag:w7h08SWVcbKlJuETdrCAfA==,type:str]
        webhook_token: ENC[AES256_GCM,data:/PTwoOAyYkvl9ux0yBIE,iv:yqFiq2jAW2+sEGPjVxtxaJTgg5L40nSV5Gsu3SPeTLI=,tag:grPoSqstebNa97actsomVg==,type:str]
    postgres:
        connStr: ENC[AES256_GCM,data:ARvML16hrpiVgzI7URvO7gD+9U7o6v6CyYQgHZMw2YJLp7btxTN0dtYtd4QJpLv1jyP8QrTymLOS/BpyAltjSCvJWCTEQuI6DbWMzjmcQZRLx8ixqqQ5LJi8pdIhpdln5hDDzDjRD2rdKmKMnL9MD1iWFnWHwjry5eYavasVFFyf23cnCjVsbuAEI2Ps/3ej2TpO0UlGSalzPzlUz+ghmn3mAHgIFw==,iv:5b5njphMn1y3COVMJw95koQkiltJhyscPKOzo7WUGNY=,tag:9Phu1M71viHtIjDwiJRJHg==,type:str]
outboxpoller:
    bot:
        token: ENC[AES256_GCM,data:IrXhW8fWHV4OBCmGyS6xX9QM619I919Y6iM5QEM9fNZ9zDyAI3lt+zPHjJZCUg==,iv:LxhC102iU7S1UAvPlno6HikQpz4DNA7G7ymAQf91um4=,tag:05PKDPeqnIfhgEjaF9TffQ==,type:str]
    postgres:
        connStr: ENC[AES256_GCM,data:4/IQEDhnya0boapsdJ45tCoFdU5/5yJNe9HddMfwd6owMRANnyn5PbBH0P80Qu7ilgmWgAOJ7XT3VEC6SLovzaNtw5BlZMp/TiXtWU5Q7IIU7m78aOtd+DnRp2f1WfvFrlD9gZRUy/ncGTFUKOS0Ewc0U9Ry51NtHDR3THzQKIAXu4Yn+1NYS8TIPlThvaOsRiLaRFOSYHMx9Voz0i3EgbOsJpnbhg==,iv:cLg21UGF8aZsLls7ldGXLzt8ykPQM2SLPPrevR66nd8=,tag:9NJc6/T38PMgDF8yFguYsw==,type:str]
poller:
    postgres:
        connStr: ENC[AES256_GCM,data:/3bhpAdtKXALgwaUO4AgUdHxSDHTsc3IawwPigw4eynA9A2ggoWvB1kmiHNfMINAA/ldJFdDAlwmbY7AAcaVQLnnwijE3GO+44uE3eSJPXz8n/UABKWwUHI8ECDecimNGt218OdZOhEvIAT6ailk7oa8eUKj8tyKd1hvU9v24pKAD27qoD7E7FkhwPFQfL52B3gRxShZd5l09624YltFPmWsixuT8w==,iv:tzvtkJFm7Y4rMBHtsCm/wSwVetkSETrcl9NuaxfT9mM=,tag:L5EYFNWpvsDHjg4ElRDz7Q==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:NI50ypzmLudKcxQ+NRxMZF1ePhr79oLSKTVumpV+lC+2+krae6Bj+sGFYBbggU+hnmKXC9dYM0U+5IeL1nqQir1xEUPesm5gzuXUICfCV4J1fa7iw1Uuv1f6d5XvIC3dTLKAewOeuFWsjG4wk36N4y/lmceZ7w/AhXGEP7WS41nlovLVOiT0jRmr0wAuj93GcS/BNwKPx5WgBKWX6hdg5w2V36xwnA==,iv:GjPlj7Ypr28hc7h/vlqRSysSrCDBNWQFUlpxs+x+mug=,tag:+TW8CRAwTgYjlOSSdc5syQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNmRTRVZDYjJiRThHWURN
            ZHorSnlTMmVlcFA5WXc0WmRoRExKUEQ3ZTIwClFXem9BaDBJaFlRREIwOXloUDE5
            T3VMS2I1aUp2K0gzMjk1a0xISldvMEEKLS0tIG1ZQ3ZxUEt2T0t3RjRCejBnbXp5
            TmkxOUE0dkgzZlBlQVRwcHV3QnhkM0EK0c+xEJRwghRWRkKqtdF0nwGK756yEqCQ
            rNFQQDq/aE76xGpYoFUWuXAT74vrA45I8dJP9iXE8rJbi1JFcLN6Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
    lastmodified: "2026-09-02T11:55:16Z"
    mac: ENC[AES256_GCM,data:cLRPTms+zspd/Zjdrw9ztGpp8W1qp0VWx1Kp6tCQQ3Nmu/YPIU/sCFVceeWFlQIYw2gLpweAXuccx++qnOj+CRbXXGe/LULdkAKerHjFkX39c59kVU6ZRN46fh+lV8ETx69bDFucLopiBzEvrNZGXR7QS5geY4fEvF4HlyEmvLQ=,iv:EfV/8GQNHO79K65zNBhh8V5Tr/RGdkm7xpGvbcpqQUc=,tag:aDXe77FMN5EJYNDT9FccLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
