apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
data:
  config-outboxpoller.yaml: |
    log_level: "info"
    tracing:
      endpoint: "jaeger-service:4318"
      service_name: "outbox-poller"
    bot:
      token: {{ .Values.bot.token }}
    postgres:
      connection: {{ .Values.postgres.connStr }}
    worker:
      count: 1
      interval: 2s
      batch_size: 10
      max_retry_count: 10



