name: build/push images and deploy to kubernetes cluster

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Build and push images
      run: make do-helm-load-images APP_TAG=$GITHUB_REF_NAME

    - name: Install SOPS
      uses: nhedger/setup-sops@v2
      with:
        version: "3.12.1"

    - name: Set up SOPS key.txt
      run: |
        mkdir -p ~/.config/sops/age/
        echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt
        chmod 600 ~/.config/sops/age/keys.txt

    - name: Install helm and age dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y age
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash
        helm plugin install https://github.com/jkroepke/helm-secrets/releases/download/v4.7.4/secrets-4.7.4.tgz --verify=false

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

    - name: Deploy with Helm
      run: |
        make do-helm-install APP_TAG=$GITHUB_REF_NAME
